// <auto-generated />
using System;
using BaseeraSecurity.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaseeraSecurity.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BaseeraSecurity.API.Entities.RateLimit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ScanCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("WindowEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WindowStart")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Identifier");

                    b.ToTable("RateLimits");
                });

            modelBuilder.Entity("BaseeraSecurity.API.Entities.Scan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuestSessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("bit");

                    b.Property<decimal>("RiskScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalVulnerabilities")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuestSessionId");

                    b.HasIndex("UserId");

                    b.ToTable("Scans");
                });

            modelBuilder.Entity("BaseeraSecurity.API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BaseeraSecurity.API.Entities.Vulnerability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Evidence")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Location")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Recommendation")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ScanId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScanId");

                    b.HasIndex("TypeId");

                    b.ToTable("Vulnerabilities");
                });

            modelBuilder.Entity("BaseeraSecurity.API.Entities.VulnerabilityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CWE_Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VulnerabilityTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CWE_Id = "CWE-79",
                            Category = "Injection",
                            Description = "Allows attackers to inject malicious scripts",
                            DisplayName = "Cross-Site Scripting (XSS)",
                            Name = "xss",
                            Severity = "Critical"
                        },
                        new
                        {
                            Id = 2,
                            CWE_Id = "CWE-89",
                            Category = "Injection",
                            Description = "Database manipulation through malicious queries",
                            DisplayName = "SQL Injection",
                            Name = "sql_injection",
                            Severity = "Critical"
                        },
                        new
                        {
                            Id = 3,
                            CWE_Id = "CWE-78",
                            Category = "Injection",
                            Description = "Execution of arbitrary system commands",
                            DisplayName = "Command Injection",
                            Name = "command_injection",
                            Severity = "Critical"
                        },
                        new
                        {
                            Id = 4,
                            CWE_Id = "CWE-798",
                            Category = "Sensitive Data",
                            Description = "API keys exposed in client-side code",
                            DisplayName = "Exposed API Keys",
                            Name = "api_keys",
                            Severity = "Critical"
                        },
                        new
                        {
                            Id = 5,
                            CWE_Id = "CWE-319",
                            Category = "Authentication",
                            Description = "Forms submitting sensitive data over HTTP",
                            DisplayName = "Insecure Forms",
                            Name = "insecure_forms",
                            Severity = "Critical"
                        },
                        new
                        {
                            Id = 6,
                            CWE_Id = "CWE-693",
                            Category = "Configuration",
                            Description = "No CSP header to prevent XSS attacks",
                            DisplayName = "Missing Content Security Policy",
                            Name = "missing_csp",
                            Severity = "High"
                        },
                        new
                        {
                            Id = 7,
                            CWE_Id = "CWE-693",
                            Category = "Configuration",
                            Description = "CSP header with unsafe directives",
                            DisplayName = "Weak Content Security Policy",
                            Name = "weak_csp",
                            Severity = "High"
                        },
                        new
                        {
                            Id = 8,
                            CWE_Id = "CWE-548",
                            Category = "Information Disclosure",
                            Description = "Configuration or backup files accessible",
                            DisplayName = "Sensitive Files Exposed",
                            Name = "sensitive_files",
                            Severity = "High"
                        },
                        new
                        {
                            Id = 9,
                            CWE_Id = "CWE-311",
                            Category = "Transport Security",
                            Description = "HTTPS page loading HTTP resources",
                            DisplayName = "Mixed Content",
                            Name = "mixed_content",
                            Severity = "Medium"
                        },
                        new
                        {
                            Id = 10,
                            CWE_Id = "CWE-523",
                            Category = "Transport Security",
                            Description = "No HTTP Strict Transport Security",
                            DisplayName = "Missing HSTS Header",
                            Name = "missing_hsts",
                            Severity = "Medium"
                        },
                        new
                        {
                            Id = 11,
                            CWE_Id = "CWE-1021",
                            Category = "UI Security",
                            Description = "Missing X-Frame-Options header",
                            DisplayName = "Clickjacking Vulnerability",
                            Name = "clickjacking",
                            Severity = "Medium"
                        },
                        new
                        {
                            Id = 12,
                            CWE_Id = "CWE-614",
                            Category = "Session Management",
                            Description = "Cookies without Secure or HttpOnly flags",
                            DisplayName = "Insecure Cookies",
                            Name = "insecure_cookies",
                            Severity = "Medium"
                        },
                        new
                        {
                            Id = 13,
                            CWE_Id = "CWE-353",
                            Category = "Supply Chain",
                            Description = "External resources without SRI checks",
                            DisplayName = "Missing Subresource Integrity",
                            Name = "missing_sri",
                            Severity = "Medium"
                        },
                        new
                        {
                            Id = 14,
                            CWE_Id = "CWE-942",
                            Category = "Configuration",
                            Description = "Overly permissive CORS policy",
                            DisplayName = "CORS Misconfiguration",
                            Name = "cors_misconfiguration",
                            Severity = "Medium"
                        },
                        new
                        {
                            Id = 15,
                            CWE_Id = "CWE-215",
                            Category = "Information Disclosure",
                            Description = "Development/debug endpoints accessible",
                            DisplayName = "Debug Pages Exposed",
                            Name = "debug_pages",
                            Severity = "Medium"
                        },
                        new
                        {
                            Id = 16,
                            CWE_Id = "CWE-601",
                            Category = "Input Validation",
                            Description = "Unvalidated redirect parameters",
                            DisplayName = "Open Redirect",
                            Name = "open_redirect",
                            Severity = "Medium"
                        },
                        new
                        {
                            Id = 17,
                            CWE_Id = "CWE-352",
                            Category = "Session Management",
                            Description = "Missing CSRF protection",
                            DisplayName = "CSRF Vulnerability",
                            Name = "csrf",
                            Severity = "Medium"
                        },
                        new
                        {
                            Id = 18,
                            CWE_Id = "CWE-477",
                            Category = "Code Quality",
                            Description = "Use of deprecated HTML tags",
                            DisplayName = "Deprecated HTML Elements",
                            Name = "deprecated_html",
                            Severity = "Low"
                        },
                        new
                        {
                            Id = 19,
                            CWE_Id = "CWE-359",
                            Category = "Privacy",
                            Description = "Third-party tracking scripts detected",
                            DisplayName = "Tracking Scripts",
                            Name = "trackers",
                            Severity = "Low"
                        },
                        new
                        {
                            Id = 20,
                            CWE_Id = "CWE-1008",
                            Category = "Other",
                            Description = "Other security issues",
                            DisplayName = "Other Vulnerability",
                            Name = "other",
                            Severity = "Medium"
                        });
                });

            modelBuilder.Entity("BaseeraSecurity.API.Entities.Scan", b =>
                {
                    b.HasOne("BaseeraSecurity.API.Entities.User", "User")
                        .WithMany("Scans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("BaseeraSecurity.API.Entities.Vulnerability", b =>
                {
                    b.HasOne("BaseeraSecurity.API.Entities.Scan", "Scan")
                        .WithMany("Vulnerabilities")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseeraSecurity.API.Entities.VulnerabilityType", "Type")
                        .WithMany("Vulnerabilities")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Scan");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("BaseeraSecurity.API.Entities.Scan", b =>
                {
                    b.Navigation("Vulnerabilities");
                });

            modelBuilder.Entity("BaseeraSecurity.API.Entities.User", b =>
                {
                    b.Navigation("Scans");
                });

            modelBuilder.Entity("BaseeraSecurity.API.Entities.VulnerabilityType", b =>
                {
                    b.Navigation("Vulnerabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
